apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-server-canary
  namespace: canary-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-server-canary
  template:
    metadata:
      labels:
        app: model-server-canary
    spec:
      enableServiceLinks: false
      containers:
        - name: model-server
          image: canarymlplatformacr32255.azurecr.io/model-server:v3
          ports:
            - containerPort: 8001
          env:
            - name: MODEL_VERSION_LABEL
              value: "stable"
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: model-server-canary
  namespace: canary-platform
spec:
  type: ClusterIP
  selector:
    app: model-server-stable
  ports:
    - port: 8001
      targetPort: 8001